#!/bin/bash

echo INFURA_API_KEY=$INFURA_API_KEY >> .env
echo MNEMONIC=$MNEMONIC >> .env
echo ETHERSCAN_API_KEY=$ETHERSCAN_API_KEY >> .env
echo COINMARKETCAP_API_KEY=$COINMARKETCAP_API_KEY >> .env
echo MYTHX_API_KEY=$MYTHX_API_KEY >> .env
echo CODE_COVERAGE=true >> .env
echo REPORT_GAS=true >> .env
echo FORKING_URL=$FORKING_URL >> .env
echo FORKING_BLOCK=$FORKING_BLOCK >> .env